// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function CancelSync() {
  return window['go']['main']['App']['CancelSync']();
}

export function CheckModsDirectory(arg1) {
  return window['go']['main']['App']['CheckModsDirectory'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultModsDir(arg1) {
  return window['go']['main']['App']['GetDefaultModsDir'](arg1);
}

export function GetSyncStatus(arg1, arg2) {
  return window['go']['main']['App']['GetSyncStatus'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartSync(arg1, arg2) {
  return window['go']['main']['App']['StartSync'](arg1, arg2);
}

export function ValidateURL(arg1) {
  return window['go']['main']['App']['ValidateURL'](arg1);
}
