// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {models} from '../models';

export function BrowseDirectory():Promise<string>;

export function CancelSync():Promise<void>;

export function CheckModsDirectory(arg1:string):Promise<boolean>;

export function GetConfig():Promise<config.Config>;

export function GetDefaultModsDir(arg1:string):Promise<string>;

export function GetSyncStatus(arg1:string,arg2:string):Promise<models.SyncResult>;

export function Quit():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartSync(arg1:string,arg2:string):Promise<void>;

export function ValidateURL(arg1:string):Promise<models.ValidationResult>;
